on:
  workflow_dispatch: {}
  push: {}
jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v4
    - uses: redhat-actions/buildah-build@v2
      with:
        tags: 42 latest
        image: mipad5-gmanka
        containerfiles: Containerfile
        build-args: |
          base_image=quay.io/pocketblue/mipad5-gnome-desktop:42
    - uses: redhat-actions/push-to-registry@v2
      with:
        tags: 42 latest
        image: mipad5-gmanka
        registry: ghcr.io/gmankab
        username: gmankab
        password: ${{ secrets.GITHUB_TOKEN }}

